var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/products/route.js")
R.c("server/chunks/f7813_next_bfe0c9c0._.js")
R.c("server/chunks/79e02_next-auth_657740b6._.js")
R.c("server/chunks/0a374_openid-client_812b4fc9._.js")
R.c("server/chunks/c1491_jose_dist_node_cjs_ad7cf29d._.js")
R.c("server/chunks/node_modules__pnpm_f47881cb._.js")
R.c("server/chunks/[root-of-the-server]__b696e4c8._.js")
R.m("[project]/.next-internal/server/app/api/products/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/.pnpm/next@15.5.4_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/products/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@15.5.4_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/products/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
